import React from "react";

const TITLES = {
  provider: "Reported by the provider's own session data or stream",
  inferred: "Derived from tool name — not reported by the provider",
  user: "Recorded from a user action in Agent Space",
  system: "Generated by Agent Space itself (status, reconciliation)",
  profile: "The working style set on the agent's profile — nothing reported it",
};

/**
 * Provenance chip: `provider` (solid), `inferred` (dashed outline), `user`,
 * `system`. Unknown values render as "unknown" so nothing is ever presented
 * as provider-reported by default.
 * @param {{ value?: string|null }} props
 */
export default function Provenance({ value }) {
  const key = TITLES[value] ? value : "unknown";
  const title = TITLES[key] ?? "Provenance not recorded";
  return (
    <span
      className={`as-prov as-prov-${key}`}
      title={title}
      aria-label={`Provenance: ${key}`}
    >
      {key}
    </span>
  );
}
